import UserInfoModel from "../models/user";

var Date1: Date = new Date();
Date1.setFullYear(2011, 6, 1);

export const userList: UserInfoModel[] = [
  {
    userId: "123",
    firstName: "sina",
    lastName: "sahraian",
    phone: "09025422471",
    username: "sina sahraian",
    email: "sinasahraada@gmail.com",
    Avatarimage: "https://randomuser.me/api/portraits/men/78.jpg",
    password: "234242",
    DateAdd: Date1,
  },
  {
    userId: "122",
    firstName: "reza",
    lastName: "rezaie",
    phone: "09177078439",
    username: "snasah",
    email: "hucsvcaubFPI@gmail.com",
    Avatarimage: "https://randomuser.me/api/portraits/men/76.jpg",
    password: "236723234263",
    DateAdd: Date1,
  },
  {
    userId: "121",
    firstName: "ehsan",
    lastName: "ebrahimi",
    phone: "091732342",
    username: "snasah",
    email: "sinasahraada@gmail.com",
    Avatarimage: "https://randomuser.me/api/portraits/men/77.jpg",
    password: "234242",
    DateAdd: Date1,
  },
  {
    userId: "121",
    firstName: "ehsan",
    lastName: "ebrahimi",
    phone: "091732342",
    username: "snasah",
    email: "sinasahraada@gmail.com",
    Avatarimage: "https://randomuser.me/api/portraits/men/60.jpg",
    password: "234242",
    DateAdd: Date1,
  },
  {
    userId: "121",
    firstName: "ehsan",
    lastName: "ebrahimi",
    phone: "091732342",
    username: "snasah",
    email: "sinasahraada@gmail.com",
    Avatarimage: "https://randomuser.me/api/portraits/men/60.jpg",
    password: "234242",
    DateAdd: Date1,
  },
  {
    userId: "121",
    firstName: "ehsan",
    lastName: "ebrahimi",
    phone: "091732342",
    username: "snasah",
    email: "sinasahraada@gmail.com",
    Avatarimage: "https://randomuser.me/api/portraits/men/60.jpg",
    password: "234242",
    DateAdd: Date1,
  },
];
